version: 2

models: 
  - name: dim_listings_cleansed
    description: Cleansed table which contains Airbnb listings.
    columns: 

      - name: listing_id
        description: primary key for the listing
        tests: 
          - unique
          - not_null

      - name: host_id
        description: Host's ID for the listing
        tests:
          - not_null
          - relationships:
                to: ref('dim_hosts_cleansed')
                field: host_id
      
      - name: room_type
        description: Type of room available
        tests:
          - accepted_values:
              values:  ['Entire home/apt',
                        'Private room',
                        'Shared room',
                        'Hotel room']

      - name : minimum_nights
        description: '{{ doc("dim_listing_cleansed_minimum_nights")}}'
        tests: 
          - positive_value